
    - name: Set Git user email
      ansible.builtin.shell: git config --global user.email "mobthomas@gmail.com"
      args:
        chdir: /backup
      delegate_to: localhost

    - name: Set Git user name
      ansible.builtin.shell: git config --global user.name "mothomas"
      args:
        chdir: /backup
      delegate_to: localhost        

    - name: Initialize Git repository if not already initialized
      ansible.builtin.shell: |
        if [ ! -d .git ]; then
          git init
          git remote add origin https://mothomas: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@github.com/mothomas/ntwrk-backup.git
        fi
      args:
        chdir: /backup
      delegate_to: localhost        

    - name: Fetch and checkout main branch
      ansible.builtin.shell: |
        git fetch origin
        git checkout -B main origin/main || git checkout -b main
      args:
        chdir: /backup
      delegate_to: localhost        

    - name: Add and commit changes
      ansible.builtin.shell: |
        git add .
        git commit -m "Backup on 05-05-24"
      args:
        chdir: /backup
      ignore_errors: yes
      delegate_to: localhost      

    - name: Push changes to main branch
      ansible.builtin.shell: git push origin main
      args:
        chdir: /backup
      ignore_errors: yes
      delegate_to: localhost      

    - name: Create and push date-based branch
      ansible.builtin.shell: |
        git checkout -b 05-05-24
        git push origin 05-05-24
      args:
        chdir: /backup
      ignore_errors: yes
      delegate_to: localhost      

        
      
        
