  - name: Pause for 5 minutes to build app cache
    ansible.builtin.pause:
      minutes: 5  


  - name: "Add output directory to git"
    ansible.builtin.shell: |
      git init
      git remote add main https://github.com/mothomas/backup.git
      git fetch origin main
      git checkout -b "27-03-24"
      git add .
      git commit -m "backup on 27"
      git push origin 27-03-24
      git checkout main
      git merge 27-03-24
      git push origin main    
    args:
      chdir: /backup
    
      
        
