#  - name: Pause for 5 minutes to build app cache
#    ansible.builtin.pause:
#      minutes: 5  

- name: "Add output directory to git"
  ansible.builtin.shell: | 
      git config --global user.email "mobthomas@gmail.com"
      git config --global user.name "mothomas"
      git init
      git remote add origin https://mothomas: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@github.com/mothomas/ntwrk-backup.git
      git fetch origin
      git checkout main
      git add .
      git commit -m "COMMIT_MESSAGE1 04-05-24"
      git push origin main
      git checkout -b 04-05-24
      git push origin 04-05-24
  args:
     chdir: /backup
  delegate_to: localhost
        
      
        
