
  - name: " setup fortinet vars"
    ansible.builtin.set_fact:
      ansible_httpapi_use_ssl: yes
      ansible_httpapi_validate_certs: no
      ansible_httpapi_port: 443
      ansible_user: admin
      ansible_password: admin123
      ansible_network_os: fortios
      ansible_connection: httpapi

  
  - name: Backup a virtual domain.
    fortinet.fortios.fortios_monitor_fact:
     selector: 'system_config_backup'
     vdom: 'root'
     params:
         scope: 'vdom'   
    register: backupinfo


  - name: Save the backup information.
    ansible.builtin.copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: "/backup/{{ sites | first }}/{{ device_roles | first }}/{{ inventory_host }}.txt"
    delegate_to: localhost
    when: backupinfo is defined 
