---
 - block:

   - name: Backup junos configuration
     vars:
       ansible_connection: netconf
     junipernetworks.junos.junos_config:
       backup: true
       backup_options:
         dir_path: /tmp/
         filename: "{{ inventory_hostname }}.txt"
     register: config_output
     
   rescue:
  
   - name: Log failed backup attempts
     ansible.builtin.shell: |
        echo "{{ inventory_hostname }} reason: failed to fetch backup, please check the backup job for exact reason" >> "{{ failed_host_list.path }}"
     when: config_output is failed
     delegate_to: localhost
