#- name: Ensure netconf is running
#  vars:
#    ansible_connection: network_cli
#  junipernetworks.junos.junos_command:
#    commands: show version
     
- block:

   - name: Backup junos configuration
     vars:
       ansible_connection: netconf
     junipernetworks.junos.junos_config:
       backup: true
       backup_options:
         dir_path: /tmp/
         filename: "{{ inventory_hostname }}.txt"
     register: config_output
     ignore_erros: yes

   - name: collect failed hosts
     ansible.builtin.set_fact:
        failed_hosts: "{{ failed_hosts + [inventory_hostname] }}"     
     when: config_output.failed
     
  rescue:
  
   - name: Log failed backup attempts
     ansible.builtin.shell: |
        echo "{{ inventory_hostname }} reason: failed to fetch backup, please check the backup job for exact reason" >> "{{ failed_host_list.path }}"
     when: config_output is failed
     delegate_to: localhost
