---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: localhost
        port: 5050
  rules:
    - name: Say Hello
      condition: event.payload.message == "Hello"
      action:
        run_job_template:
          name: network-eda-backup
          organization: devlab
          job_args:
            extra_vars:
              hosts: "{{ event.payload.hosts }}"
    - name: Didn't hear Hello
      condition: event.payload.message != "Hello"
      action:
        debug:
          msg: "You said, '{{ event.payload.hosts }}'. Is that what you meant to say?"