---

- name: Setup | Create a temp dir for git
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: git_temp_dir
  delegate_to: localhost

- name: Setup | setup git backup repo url
  ansible.builtin.set_fact:
    git_backuprepo_url: "https://{{ git_user_name }}:{{ git_token }}@{{ git_url }}/{{ git_repo_name }}.git"
  no_log: true
  delegate_to: localhost  

- name: Baremetal | Git set user and token
  ansible.builtin.shell: |
    git config user.email "{{ git_user_email }}"
    git config user.name "{{ git_user_name }}"
    git config --global credential.helper store
    git config --global credential.helper 'cache --timeout=300'
    git config --global github.user "{{ git_user_name }}"
    git config --global github.token "{{ git_token }}"
  args:
    chdir: /backup
  delegate_to: localhost    

- name:  Clone down the backup repo
  ansible.builtin.git:
    repo: "{{ git_backuprepo_url }}"
    dest: "{{ git_temp_dir.path }}/git"
    clone: true
    version: "main"
  delegate_to: localhost    
  
      
