---
- name: Retrieve network configurations
  hosts: "{{ hosts }}"
  gather_facts: False

  pre_tasks:

    - name: Create temporary file
      ansible.builtin.tempfile:
         state: file
         suffix: failed
      register: failed_host_list
      run_once: true
      delegate_to: localhost

    - name: find Devices that are active but will be excluded from the play.
      ansible.builtin.blockinfile:
        path: "{{ failed_host_list.path }}"
        block: |
          {% for h in groups[hosts] if hostvars[h].ansible_network_os is not defined or hostvars[h].ansible_network_os not in supported_platforms %}
          {{ inventory_hostname }} reason: device platform not available in NetBox or not supported
          {% endfor %}
      delegate_to: localhost 
    
      

  tasks:
  

    - name: Backup configuration
      ansible.builtin.include_role:
        name: "../roles/backup"
      when: 
        - ansible_network_os is defined

    - name: Save configuration to backup folder
      ansible.builtin.copy:
        src: "{{ config_output.backup_path }}"
        dest: "/backup/{{ sites | first }}/{{ device_roles | first }}/"
        mode: "644"
      when: config_output is defined
      delegate_to: localhost

#    - name: setting up backup folder and init git
#      ansible.builtin.include_role:
#      ansible.builtin.import_role:  
#        name: "../roles/setup"
#      run_once: true               
#      delegate_to: localhost
#
    - name: Backup configuration
      ansible.builtin.import_tasks:
#      ansible.builtin.include_role:
        file: "upload.yml"
      run_once: true
      delegate_to: localhost
    
    - name: set content
      ansible.builtin.set_fact:
        file_content: "{{ lookup('file', failed_host_list.path) }}"
      run_once: true
      delegate_to: localhost        

    - name: debug
      ansible.builtin.debug:
        msg: "{{ file_content }}"
      run_once: true
      delegate_to: localhost
      

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 10
      
      
      
      
