---
- name: Retrieve network configurations
  hosts: "{{ hosts }}"
  gather_facts: False

  tasks:
  
    - name: Initialize failed_hosts list
      ansible.builtin.set_fact:
        hosts_failed: {}
      run_once: true
      delegate_to: localhost

    - name: Check for necessary data platform, site, device_role in netbox
      ansible.builtin.set_fact:
        hosts_failed: "{{ hosts_failed | combine({'hostname': inventory_hostname, 'reason': 'device platform info not available in NetBox or not supported'}) }}"
      when: ansible_network_os is not defined or ansible_network_os not in supported_platforms
      delegate_facts: true
      delegate_to: localhost

    - name: Backup configuration
      ansible.builtin.include_role:
        name: "../roles/backup"
      when: 
        - ansible_network_os is defined

    - name: Save configuration to backup folder
      ansible.builtin.copy:
        src: "{{ config_output.backup_path }}"
        dest: "/backup/{{ sites | first }}/{{ device_roles | first }}/"
        mode: "644"
      when: config_output is defined
      delegate_to: localhost

#    - name: Pause for 5 minutes to build app cache
#      ansible.builtin.pause:
#        minutes: 10

#    - name: setting up backup folder and init git
#      ansible.builtin.include_role:
#      ansible.builtin.import_role:  
#        name: "../roles/setup"
#      run_once: true               
#      delegate_to: localhost
#
    - name: Backup configuration
      ansible.builtin.import_tasks:
#      ansible.builtin.include_role:
        file: "upload.yml"
      run_once: true
      delegate_to: localhost
      
    - ansible.builtin.debug:
         msg: " below hosts failed   {{ hosts_failed }} "
      run_once: true
      delegate_to: localhost
            
      
      
      
      
      
