---
- name: Retrieve network configurations
  hosts: "{{ hosts }}"
  gather_facts: False

  tasks:
  
    - name: populate host list without necessary data platform, site, device_role missing in netbox
      ansible.builtin.set_fact:
        failed_hosts: "{{ failed_hosts | default([]) + [{'hostname': {{ inventory_hostname }}, 'reason': 'device platform not available in NetBox'}] }}"
      when: 
        - ansible_network_os is not defined

    - name: Backup configuration
      ansible.builtin.include_role:
        name: "../roles/backup"
      when: 
        - ansible_network_os is defined

    - name: Save configuration to backup folder
      ansible.builtin.copy:
        src: "{{ config_output.backup_path }}"
        dest: "/backup/{{ sites | first }}/{{ device_roles | first }}/"
        mode: "644"
      when: config_output is defined
      delegate_to: localhost

#    - name: Pause for 5 minutes to build app cache
#      ansible.builtin.pause:
#        minutes: 10

#    - name: setting up backup folder and init git
#      ansible.builtin.include_role:
#      ansible.builtin.import_role:  
#        name: "../roles/setup"
#      run_once: true               
#      delegate_to: localhost
#
    - name: Backup configuration
      ansible.builtin.import_tasks:
#      ansible.builtin.include_role:
        file: "upload.yml"
      run_once: true
      delegate_to: localhost
      
    - ansible.builtin.debug:
         msg: " below hosts failed {{ failed_host }}
      
      
      
      
      
      
      
      
      
      - 
