---
- name: Retrieve network configurations
  hosts: "{{ hosts }}"
  serial: 3
  gather_facts: False

  tasks:
#    - name: setting up backup folder and init git 
#      ansible.builtin.include_role:
#        name: "../roles/setup"
#      run_once: true  
    
    - name: Backup configuration
      ansible.builtin.include_role:
        name: "../roles/backup"
      when: ansible_network_os is defined

    - name: Create time stamp for play
      ansible.builtin.set_fact:
        datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"
      run_once: true

    - name: Save configuration to backup folder
      ansible.builtin.copy:
        src: "{{ config_output.backup_path }}"
        dest: "/backup/{{ sites | first }}/{{ device_roles | first }}/"
        mode: "644"
      when: config_output is defined
      delegate_to: localhost

 #   - name: Backup configuration
 #     ansible.builtin.include_role:
 #       name: "../roles/upload"
 #     run_once: true
    
      
